name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build container
        run: docker build -t $(echo ${{ secrets.DOCKER_REGISTRY }}/sass-factory:$(echo $GITHUB_SHA | head -c7)) .

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo ${{ secrets.DOCKER_REGISTRY }}/sass-factory:$(echo $GITHUB_SHA | head -c7))

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Log in to DigitalOcean Container Registry
            doctl registry login
            # Pull the latest image
            docker pull $(echo ${{ secrets.DOCKER_REGISTRY }}/sass-factory:$(echo $GITHUB_SHA | head -c7))
            # Stop and remove the old container
            docker stop sass-factory || true
            docker rm sass-factory || true
            # Run the new container
            docker run -d -p 3000:3000 --name sass-factory $(echo ${{ secrets.DOCKER_REGISTRY }}/sass-factory:$(echo $GITHUB_SHA | head -c7))
